### ISSUE TITLE
Not able to run in windows ?

### ISSUE THREAD

**Issue by Nagamani732** [lcskrishna/onnx-parser#2]
I installed cmake 3.11.1 and protobuf 3.51 (c++ installation) and built successfully but not able to run. After the successful build and I just opened the ALL_BUILD project which was created after building in visual studio. It shows an error in onnx namespace. The project was not able to find the onnx namespace.

Could you please help me in this regard ?

**Comment by lcskrishna** [comment]
This project has a pre-requisite to use it on Ubuntu 16.04 for now. 
Try out this project by installing ubuntu 16.04 in a virtual box.

**Comment by Nagamani732** [comment]
Hi, Thanks for the reply. I noticed that prerequisite but then my intention is to get run on windows. Is there any other way to do it?

**Comment by lcskrishna** [comment]
Hi, Please email me personally. We can discuss about it.

**Comment by lcskrishna** [comment]
Closing this issue. Feel free to reopen it again if you find any problem.
